import pygame

PREVIOUS_EVENT = pygame.USEREVENT + 2
NEXT_EVENT = pygame.USEREVENT + 3
SOLVE_UCS_EVENT = pygame.USEREVENT + 4
SOLVE_ASTARMAN_EVENT = pygame.USEREVENT + 5
SOLVE_DFS_EVENT = pygame.USEREVENT + 6
SOLVE_BFS_EVENT = pygame.USEREVENT + 7
